osx_image: xcode11.6
language: objective-c
script:
  - xcodebuild clean test -enableCodeCoverage YES -workspace Example/Ranger.Swift.TrackerV1.xcworkspace -scheme Ranger.Swift.TrackerV1-Example -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
deploy:
  skip_cleanup: true
  provider: script
  script: pod trunk push
  on:
    tags: true